version: '3.8'

services:
  user-service:
    container_name: user-service
    image: my-followers:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: npm run start:prod
    networks:
      - kong-net
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
